#!/usr/bin/env python3
"""
Fill the official COP-PILOT OC1 Proposal Guidelines DOCX template
with generated proposal content from the pipeline.

Usage:
    python3 scripts/fill-cop-pilot-docx.py

Input:
    - results/cop-pilot/scientific-proposal.json (generated by pipeline)
    - grants/cop-pilot-oc1/COP-PILOT_OC1_Proposal_Guidelines-2.docx (official template)

Output:
    - results/cop-pilot/SmartLoop-COP-PILOT-OC1-Proposal.docx
"""

import json
import os
import re
import copy
from pathlib import Path
from docx import Document
from docx.shared import Pt, Cm, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

ROOT_DIR = Path(__file__).parent.parent
PROPOSAL_JSON = ROOT_DIR / "results" / "cop-pilot" / "scientific-proposal.json"
TEMPLATE_DOCX = ROOT_DIR / "grants" / "cop-pilot-oc1" / "COP-PILOT_OC1_Proposal_Guidelines-2.docx"
OUTPUT_DOCX = ROOT_DIR / "results" / "cop-pilot" / "SmartLoop-COP-PILOT-OC1-Proposal.docx"


def load_proposal() -> dict:
    with open(PROPOSAL_JSON, "r", encoding="utf-8") as f:
        return json.load(f)


def set_paragraph_font(paragraph, font_name="Arial", font_size=10, bold=False, color=None):
    """Set font properties for all runs in a paragraph."""
    for run in paragraph.runs:
        run.font.name = font_name
        run.font.size = Pt(font_size)
        run.font.bold = bold
        if color:
            run.font.color.rgb = color


def add_formatted_text(doc, text, style="Normal", font_size=10):
    """Add text to the document, handling markdown-like formatting."""
    lines = text.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()

        # Skip empty lines
        if not line:
            i += 1
            continue

        # Markdown table detection
        if "|" in line and i + 1 < len(lines) and "|" in lines[i + 1]:
            # Collect all table lines
            table_lines = []
            while i < len(lines) and "|" in lines[i]:
                stripped = lines[i].strip()
                if stripped and not all(c in "|-: " for c in stripped):
                    table_lines.append(stripped)
                i += 1

            if table_lines:
                add_markdown_table(doc, table_lines, font_size)
            continue

        # Headers
        if line.startswith("### "):
            p = doc.add_paragraph()
            run = p.add_run(line[4:].strip())
            run.font.name = "Arial"
            run.font.size = Pt(font_size)
            run.font.bold = True
            p.space_after = Pt(4)
            p.space_before = Pt(8)
            i += 1
            continue

        if line.startswith("## "):
            # Skip duplicate section headers (already in template)
            header_text = line[3:].strip()
            # Check if it's a numbered section like "1.1.1 Concept..."
            if re.match(r"^\d+\.\d+", header_text):
                i += 1
                continue
            p = doc.add_paragraph()
            run = p.add_run(header_text)
            run.font.name = "Arial"
            run.font.size = Pt(font_size + 1)
            run.font.bold = True
            p.space_after = Pt(4)
            p.space_before = Pt(10)
            i += 1
            continue

        # Bullet points
        if line.startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            add_inline_formatting(p, line[2:].strip(), font_size)
            i += 1
            continue

        # Numbered lists
        if re.match(r"^\d+\.\s", line):
            p = doc.add_paragraph(style="List Bullet")
            add_inline_formatting(p, line, font_size)
            i += 1
            continue

        # Regular paragraph
        p = doc.add_paragraph()
        add_inline_formatting(p, line.strip(), font_size)
        p.paragraph_format.space_after = Pt(4)
        p.paragraph_format.space_before = Pt(2)
        i += 1


def add_inline_formatting(paragraph, text, font_size=10):
    """Handle **bold** and other inline markdown formatting."""
    # Split on **bold** markers
    parts = re.split(r"(\*\*.*?\*\*)", text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.font.bold = True
        else:
            run = paragraph.add_run(part)
        run.font.name = "Arial"
        run.font.size = Pt(font_size)


def add_markdown_table(doc, table_lines, font_size=9):
    """Parse markdown table lines and add a formatted Word table."""
    rows_data = []
    for line in table_lines:
        cells = [c.strip() for c in line.strip("|").split("|")]
        rows_data.append(cells)

    if not rows_data:
        return

    num_cols = max(len(row) for row in rows_data)

    # Normalize row lengths
    for row in rows_data:
        while len(row) < num_cols:
            row.append("")

    table = doc.add_table(rows=len(rows_data), cols=num_cols)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    for ri, row_data in enumerate(rows_data):
        for ci, cell_text in enumerate(row_data):
            cell = table.cell(ri, ci)
            cell.text = ""
            p = cell.paragraphs[0]
            add_inline_formatting(p, cell_text, font_size)
            p.paragraph_format.space_after = Pt(1)
            p.paragraph_format.space_before = Pt(1)

            # Bold header row
            if ri == 0:
                for run in p.runs:
                    run.font.bold = True

    # Add spacing after table
    doc.add_paragraph()


def clear_placeholder_content(doc, start_idx, end_idx):
    """Remove paragraphs between start and end indices (placeholder/instruction text)."""
    # We'll track which paragraphs to remove
    to_remove = []
    for i in range(start_idx, min(end_idx, len(doc.paragraphs))):
        to_remove.append(doc.paragraphs[i])

    for p in to_remove:
        element = p._element
        element.getparent().remove(element)


def build_proposal_docx(proposal: dict):
    """Build a new DOCX from scratch using the proposal data, following COP-PILOT template structure."""
    doc = Document()

    # Set default font
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Arial"
    font.size = Pt(10)

    # Set margins
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    # === PROJECT SUMMARY ===
    h = doc.add_heading("PROJECT SUMMARY", level=1)
    for run in h.runs:
        run.font.name = "Arial"

    p = doc.add_paragraph()
    run = p.add_run("Project Title: ")
    run.font.bold = True
    run.font.name = "Arial"
    run.font.size = Pt(10)
    run = p.add_run("SmartLoop — Closed-Loop Building Automation Service for Municipal Facility Management")
    run.font.name = "Arial"
    run.font.size = Pt(10)

    p = doc.add_paragraph()
    run = p.add_run("Acronym: ")
    run.font.bold = True
    run.font.name = "Arial"
    run.font.size = Pt(10)
    run = p.add_run("SmartLoop")
    run.font.name = "Arial"
    run.font.size = Pt(10)

    p = doc.add_paragraph()
    run = p.add_run("Target Cluster: ")
    run.font.bold = True
    run.font.name = "Arial"
    run.font.size = Pt(10)
    run = p.add_run("☒ Cluster 2: Smart Sustainable IoT Solutions (Valencia)")
    run.font.name = "Arial"
    run.font.size = Pt(10)

    p = doc.add_paragraph()
    run = p.add_run("Summary:")
    run.font.bold = True
    run.font.name = "Arial"
    run.font.size = Pt(10)

    # Extract just the summary text (remove title/acronym/cluster lines if present)
    summary_text = proposal.get("projectSummary", "")
    # Remove any leading metadata lines
    summary_lines = summary_text.split("\n")
    clean_summary = []
    for line in summary_lines:
        if line.strip().startswith("**Project Title") or line.strip().startswith("**Acronym") or \
           line.strip().startswith("**Target Cluster") or line.strip().startswith("**Target Challenge"):
            continue
        if line.strip():
            clean_summary.append(line.strip())
    summary_body = " ".join(clean_summary)

    p = doc.add_paragraph()
    add_inline_formatting(p, summary_body, 10)
    p.paragraph_format.space_after = Pt(6)

    doc.add_page_break()

    # === SECTION 1: EXCELLENCE ===
    h = doc.add_heading("1  Excellence", level=1)
    for run in h.runs:
        run.font.name = "Arial"

    h2 = doc.add_heading("1.1 Detailed Description", level=2)
    for run in h2.runs:
        run.font.name = "Arial"

    # 1.1.1 Concept and Objectives
    h3 = doc.add_heading("1.1.1  Concept and Objectives", level=3)
    for run in h3.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("conceptAndObjectives", ""))

    # 1.1.2 State of the Art and Innovation
    h3 = doc.add_heading("1.1.2  State of the Art and Innovation", level=3)
    for run in h3.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("stateOfTheArt", ""))

    # 1.1.3 Relevance to COP-PILOT Scope
    h3 = doc.add_heading("1.1.3  Relevance to COP-PILOT Scope", level=3)
    for run in h3.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("copPilotRelevance", ""))

    # 1.1.4 Data Management
    h3 = doc.add_heading("1.1.4  Data Management", level=3)
    for run in h3.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("dataManagement", ""))

    # 1.2 Infrastructure Requirements
    h2 = doc.add_heading("1.2  Infrastructure Requirements", level=2)
    for run in h2.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("infrastructureRequirements", ""))

    doc.add_page_break()

    # === SECTION 2: IMPACT ===
    h = doc.add_heading("2  Impact", level=1)
    for run in h.runs:
        run.font.name = "Arial"

    h2 = doc.add_heading("2.1  Expected Impact and Sustainability", level=2)
    for run in h2.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("expectedImpact", ""))

    h2 = doc.add_heading("2.2  Expected Outcomes", level=2)
    for run in h2.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("expectedOutcomes", ""))

    doc.add_page_break()

    # === SECTION 3: QUALITY AND EFFICIENCY ===
    h = doc.add_heading("3  Quality and Efficiency of the Implementation", level=1)
    for run in h.runs:
        run.font.name = "Arial"

    h2 = doc.add_heading("3.1  Work Plan and Timeline", level=2)
    for run in h2.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("workPlanAndTimeline", ""))

    h2 = doc.add_heading("3.2  Team Qualifications", level=2)
    for run in h2.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("teamQualifications", ""))

    h2 = doc.add_heading("3.3  Funding & Justification", level=2)
    for run in h2.runs:
        run.font.name = "Arial"
    add_formatted_text(doc, proposal.get("fundingJustification", ""))

    # === REFERENCES ===
    h = doc.add_heading("References", level=1)
    for run in h.runs:
        run.font.name = "Arial"

    for ref in proposal.get("bibliography", []):
        p = doc.add_paragraph()
        run = p.add_run(ref)
        run.font.name = "Arial"
        run.font.size = Pt(9)
        p.paragraph_format.space_after = Pt(2)

    return doc


def main():
    print("=== COP-PILOT OC1 Proposal DOCX Generator ===\n")

    if not PROPOSAL_JSON.exists():
        print(f"Error: Proposal JSON not found at {PROPOSAL_JSON}")
        print("Run the pipeline first: pnpm --filter @researcher/backend cop-pilot")
        return

    print(f"Loading proposal from: {PROPOSAL_JSON}")
    proposal = load_proposal()

    # Count words
    total_words = sum(
        len(v.split()) if isinstance(v, str) else sum(len(x.split()) for x in v) if isinstance(v, list) else 0
        for v in proposal.values()
    )
    print(f"Proposal word count: ~{total_words} words")

    print(f"Building DOCX document...")
    doc = build_proposal_docx(proposal)

    # Save
    OUTPUT_DOCX.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(OUTPUT_DOCX))
    print(f"\n✓ Saved to: {OUTPUT_DOCX}")
    print(f"  Open in Word/LibreOffice, verify formatting, then copy into the official template if needed.")
    print(f"  Font: Arial 10pt | Margins: 2.5cm | Max 12 pages")


if __name__ == "__main__":
    main()
